Aim:write a python program to import and export data using pandas library function.

Import data : bring external data to python.
use pandas to import : pd.read_csv() , pd.read_excel(),pd.read_json().

We can perform some operations on this data using pandas.


Export data : take data(updated) from python (dataframe) and save it somewhere or to the same file.
use pandas to export : df.to_csv() , df.to_excel() , df.to_json()

Note- When you export the data from datframe to csv(or any) then pandas automatically include the row numbers as the very first column which result into unnamed columns , if you read and write file repeatdly thne pandas will add new index column everytime. So to prevent this behaviour use index=False.

                                                             importing and exporting csv file

In [59]:

#IMPORT:
import pandas as pd
df = pd.read_csv("datasets/marvel_ratings.csv") #importing dataset.
df.head(5) #importing only first 5 rows.
df #importing whole dataset.

                         title  year source  score
0              Captain America  1944   IMDb    5.3
1              Captain America  1944   TMDB    5.4
2       The Amazing Spider-Man  1977   IMDb    6.2
3       The Amazing Spider-Man  1977   TMDB    6.3
4                   Spider-Man  1977   IMDb    6.2
..                         ...   ...    ...    ...
549                 Wonder Man  2026   IMDb    7.4
550                 Wonder Man  2026   TMDB  7.019
551      Daredevil: Born Again  2026   IMDb    7.8
552      Daredevil: Born Again  2026   TMDB    7.0
553  Spider-Man: Brand New Day  2026   TMDB    0.0

[554 rows x 4 columns]

In [26]:
#EXPORT
import pandas as pd
df = pd.read_csv("datasets/marvel_ratings.csv") #importing dataset.
df.drop_duplicates() #removing all duplicate records.
df.to_csv("datasets/marvel_ratings_export.csv" , index = False)

                                                         importing and exporting excel file

In [60]:
#IMPORT:
import pandas as pd
df = pd.read_excel("datasets/marvel_ratings.xls") #importing dataset.
df.head()

                    title  year source score
0         Captain America  1944   IMDb   5.3
1         Captain America  1944   TMDB   5.4
2  The Amazing Spider-Man  1977   IMDb   6.2
3  The Amazing Spider-Man  1977   TMDB   6.3
4              Spider-Man  1977   IMDb   6.2

In [55]:
#EXPORT:
import pandas as pd
df = pd.read_excel("datasets/marvel_ratings.xls")
df.info() #summary of dataframe
df.to_excel("/Users/kalpanarana/Downloads/Cola dataset in xlsx.xlsx" , index = False)

<class 'pandas.DataFrame'>
RangeIndex: 554 entries, 0 to 553
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   554 non-null    str
 1   year    554 non-null    int64
 2   source  554 non-null    str
 3   score   369 non-null    object
dtypes: int64(1), object(1), str(2)
memory usage: 17.4+ KB

                                                     importing and exporting json file

In [61]:
#IMPORT:
import pandas as pd
df = pd.read_json("datasets/marvel_ratings.json") #importing dataset.
df

                         title  year source  score
0              Captain America  1944   IMDb    5.3
1              Captain America  1944   TMDB    5.4
2       The Amazing Spider-Man  1977   IMDb    6.2
3       The Amazing Spider-Man  1977   TMDB    6.3
4                   Spider-Man  1977   IMDb    6.2
..                         ...   ...    ...    ...
549                 Wonder Man  2026   IMDb    7.4
550                 Wonder Man  2026   TMDB  7.019
551      Daredevil: Born Again  2026   IMDb    7.8
552      Daredevil: Born Again  2026   TMDB    7.0
553  Spider-Man: Brand New Day  2026   TMDB    0.0

[554 rows x 4 columns]

In [58]:
#EXPORT:
import pandas as pd
df = pd.read_json("datasets/marvel_ratings.json")
df.value_counts() #checking the no. of missing values in each record.
df.to_json("datasets/marvel_ratings.json" , index = False)